### ISSUE TITLE
[기능개선] sub project Realtime-processing의 frame drop 문제

### ISSUE THREAD

**Issue by ajs3801** [ajs3801/LGuplus#3]
## Realtime-processing.py에서 frame drop이 일어나고 있습니다.

[m1 pro - result]
<img width="76" alt="Screen Shot 2022-06-14 at 9 49 30 AM" src="https://user-images.githubusercontent.com/43237393/173470627-d6212fee-a4ff-4ba8-8df9-6253570188b5.png">

<img width="79" alt="Screen Shot 2022-06-14 at 9 49 47 AM" src="https://user-images.githubusercontent.com/43237393/173470638-db312cce-7621-4581-8ae2-3e348a57f015.png">

일단 파이썬 멀티쓰레드나 멀티프로세스로 해결하려고 하는데

더 좋은 의견 있으면 comment 남겨주세요 : )

**Comment by ajs3801** [comment]
일단 다음과 같이 다섯개의 frame을 가져오는게 아니라
cap.read()는 한번만 써서 frame을 복사하는 방법으로 fps를 조금 개선했습니다
```python
ret, frame = cap.read()     #프레임별 캡쳐
frame1 = frame
frame2 = frame
frame3 = frame
frame4 = frame
```

**Comment by ajs3801** [comment]
```python
detect_common_objects(image, confidence=0.5, nms_thresh=0.3, model='yolov3', enable_gpu=False)
```

yolo에서 frame drop이 발생하므로 좀 가벼운 모델인 model = 'yolov3-tiny'을 사용하는 것도 하나의 대안이 될 듯 합니다

**Comment by SiHeonChae** [comment]
멀티 프로세싱으로 frame drop문제 개선했습니다.
하지만 이로 인해 여러 영상을 한 창에 띄우지 못하는 문제가 새로 발생했습니다
